export const TOGGLE_NAV = "TOGGLE_NAV";
export const CLOSE_NAV = "CLOSE_NAV";

export const INCREASE_LEVEL = "INCREASE_LEVEL";
export const DECREASE_LEVEL = "DECREASE_LEVEL";

export const INCREASE_TASKS_COMPLETED = "INCREASE_TASKS_COMPLETED";
export const DECREASE_TASKS_COMPLETED = "DECREASE_TASKS_COMPLETED";

export const INCREASE_TASK_ITEMS_FOUND = "INCREASE_TASK_ITEMS_FOUND";
export const DECREASE_TASK_ITEMS_FOUND = "DECREASE_TASK_ITEMS_FOUND";

export const INCREASE_HIDEOUT_ITEMS_FOUND = "INCREASE_HIDEOUT_ITEMS_FOUND";
export const DECREASE_HIDEOUT_ITEMS_FOUND = "DECREASE_HIDEOUT_ITEMS_FOUND";

export const CHANGE_TRADER_FILTER = "CHANGE_TRADER_FILTER";
export const CHANGE_FILTER_BY = "CHANGE_FILTER_BY";
export const CHANGE_STATUS_FILTER = "CHANGE_STATUS_FILTER";