/* User data */
export const TOGGLE_NAV = "TOGGLE_NAV";
export const CLOSE_NAV = "CLOSE_NAV";
export const CHANGE_PATH = "CHANGE_PATH";

export const INCREASE_LEVEL = "INCREASE_LEVEL";
export const DECREASE_LEVEL = "DECREASE_LEVEL";

export const LOAD_USER_DATA = "LOAD_USER_DATA";
export const LOAD_TASK_DATA = "LOAD_TASK_DATA";
export const LOAD_HIDEOUT_DATA = "LOAD_HIDEOUT_DATA";
export const LOAD_ITEM_DATA = "LOAD_ITEM_DATA";

export const CHANGE_TRADER_FILTER = "CHANGE_TRADER_FILTER";
export const CHANGE_FILTER_BY = "CHANGE_FILTER_BY";
export const CHANGE_STATUS_FILTER = "CHANGE_STATUS_FILTER";

export const ADD_COMPLETED_TASK = "ADD_COMPLETED_TASK";
export const UNDO_COMPLETED_TASK = "UNDO_COMPLETED_TASK";
export const UPDATE_ACTIVE_TASKS = "UPDATE_ACTIVE_TASKS";
export const UPDATE_LOCKED_TASKS = "UPDATE_LOCKED_TASKS";
export const UPDATE_COMPLETED_TASKS = "UPDATE_COMPLETED_TASKS";

/* Hideout */
export const UPDATE_STATION_DATA = "UPDATE_STATION_DATA";
export const INCREASE_HIDEOUT_LEVEL = "INCREASE_HIDEOUT_LEVEL";
export const DECREASE_HIDEOUT_LEVEL = "DECREASE_HIDEOUT_LEVEL";
export const INCREASE_HIDEOUT_ITEM_COUNT = "INCREASE_HIDEOUT_ITEM_COUNT";

/* Items needed */
export const UPDATE_ITEMS_DATA = "UPDATE_ITEMS_DATA";
export const INCREASE_FOUND_ITEM_COUNT = "INCREASE_FOUND_ITEM_COUNT";
export const DECREASE_FOUND_ITEM_COUNT = "DECREASE_FOUND_ITEM_COUNT";
export const TOGGLE_COMPLETION_STATUS = "TOGGLE_COMPLETION_STATUS";
export const COMPLETE_ITEMS_FROM_TASK = "COMPLETE_ITEMS_FROM_TASK";